flags:
  log.parameters: false
  log.requests: true
  use:
    ssl: true
    http2: true
    jdbc: true
    postgres: true
    h2: false
  default-jdbc-client: "${JDBC_CLIENT_NAME:default-jdbc-client-pg}"


server.ssl:
  key-store: classpath:server.p12
  key-store-password: test123
  key-password: test123
  keystoreType: PKCS12
  enabled: ${flags.use.ssl}

server:
  http2:
    enabled: ${flags.use.http2}

endpoints:
  enabled: true
  trace:
    enabled: false
  health:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true

  cors.allowed-origins: http://localhost
  cors.allowed-methods: GET,POST

server.error.whitelabel.enabled: false


secrets:
  enabled: true
  config:
    key-error-decision: "identity"
    providers:
      - name: vault
        mount: "${SECRETS_LOCATION:/vault/secrets}"
        key: "${KEY_FILE:/tmp/key}"
        #if default is not set at entry level, fail, empty, identity
        error-decision: empty
        #additional entries in one file
        entries-location: "${PROPERTIES_LOCATION:/vault/others.properties}"
        ignore-resource-failure: true


datasource.jdbc:
  enabled: ${flags.use.jdbc}
  ref:

    - name: default-jdbc-client-pg
      driver: postgresql
      username: "secret::vault::postgres_username:-starter_user"
      password: "secret::vault::postgres_password:-starter"
      host: ${POSTGRES_HOST:localhost}
      port: ${POSTGRES_PORT:5432}
      database: starter
      enabled: ${flags.use.postgres}
